service: video-fetcher-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  handler:
    handler: index.handler
    events:
      - s3:
          bucket: invigilator-video-input-bucket
          event: s3:ObjectCreated:*
          #existing: true
    role: videoFetcherLambdaIAMRole

resources:
  Resources:
    videoFetcherLambdaIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: video-fetcher-lambda-role
        Path: /service-role/
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "sts:AssumeRole"
              Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
